### ISSUE TITLE
[FEATURE] Add option for task to recur based on completion date/time

### ISSUE THREAD

**Issue by shbach** [ahmet-cetinkaya/whph#133]
### Is your feature request related to a problem?

Right now the default behavior and only option for recurring tasks is for them to recur based on the deadline date. However, certain recurring tasks require recurrence based off the completion date. e.g. I water my plant once a week on Mondays. If I neglect to water the plant until Friday, I would want to next water the plant 7 days from Friday. If instead I watered next on Monday that would be only 3 days which is too soon.

### Describe the solution you'd like

Add an option for recurrence to occur based off completion date/time, instead of the defaut behavior which is based off the deadline date/time.

For reference look at how the to-do app Sleek deals with this: https://github.com/ransome1/sleek/wiki/Recurring-todos-(rec:)#strict-recurrences-based-on-due-date-instead-of-date-of-completion

### Feature Category

None

**Comment by ahmet-cetinkaya** [comment]
Hi, @shbach. Thank you for raising this issue and sharing your feedback.

I have implemented the flow for task recurrence to be based on the actual completion date. This ensures that if a task is completed late, the next instance will be scheduled relative to when it was actually finished, preventing a backlog of overdue tasks. If the task is completed ahead of schedule, the original planned dates are preserved to maintain your routine.

These improvements are already merged and will be available in the next release. Thanks again for helping me improve WHPH! 🚀

**Comment by shbach** [comment]
@ahmet-cetinkaya Unfortunately it appears you misunderstand the use case and what you implemented does not solve the issue and actually causes more issues.

There are two types of recurring tasks:

1. Tasks that always need to be completed by a certain date/point of time. e.g. Paying the bills at the end of the month. If it is completed early, you still want the next recurring task to be at the end of the next month, you don't want the want the due date shifting up. Also, if the task is completed late, you still want the next recurring task to be end of the next month, not to be shifted back later otherwise you will be always late on paying the bills.
2. Tasks that always need be completed after a certain time interval has elapsed from the last time it was completed. e.g. You have a password that expires every 90 days from when it was last changed. If you change it early at 80 days since you had time, you still want the next recurrence to be 90 days from when you completed it. If you were late and changed the password at 100 days, you still want the recurrence to be 90 days from when you actually completed the task.


What you have implemented will cause issues for both types of tasks. For #1 tasks, late  completed tasks will keep shifting the due dates later and later, making you perpetually late on completing the tasks. For #2 tasks, if tasks are completed early, the next recurring tasks will be completely off sync with when the task actually needs to reoccur. 


So tasks need the option for recurrence to occur based off the completion date/time OR off the deadline date/time. Let me know you need further clarification.

**Comment by shbach** [comment]
@ahmet-cetinkaya Did you get a chance to review my comment? The way recurrence is currently implemented is problematic and makes this app unusable because the recurrences are unreliable.

**Comment by ahmet-cetinkaya** [comment]
@shbach, sorry for the late response. Completion-day-based recurrence for tasks is optional. There is an option in the recurrence settings that allows you to set the task based on either the deadline or the completion day.

<img width="414" height="90" alt="Image" src="https://github.com/user-attachments/assets/6656d0a3-19d4-453d-b345-90b6762e5ffd" />
